### ISSUE TITLE
2장 환경 구성 관련 문의드립니다. 

### ISSUE THREAD

**Issue by devms0201** [onlybooks/kafka2#11]
안녕하세요. 먼저 좋은 책 써 주셔서 감사합니다. 덕분에 열심히 공부하고있습니다. 

책 초반부 실습 환경 설정중에 문제가 있어서 구글링을 해보아도 초보자인 저에겐 좀 여려운 부분이라서 이렇게 이슈 만듭니다. 
AWS 환경에서 설정하여 실습을 진행중에 있습니다. 

설치는 완료하였고 첫 토픽 생성을 위하여 

``` /usr/local/kafka/bin/kafka-topics.sh --bootstrap-server peter-kafka01.foo.bar:9092 --create --topic peter-overview01 --partitions 1 --replication-factor 3 ``` 
를 실행하였습니다. 
그랬더니 아래와 같은 오류가 나오면서 실행이 불가능합니다. 

```
WARN Couldn't resolve server peter-kafka01.foo.bar:9092 from bootstrap.servers as DNS resolution failed for peter-kafka01.foo.bar (org.apache.kafka.clients.ClientUtils)
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:499)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:63)
	at kafka.admin.TopicCommand$AdminClientTopicService$.createAdminClient(TopicCommand.scala:216)
	at kafka.admin.TopicCommand$AdminClientTopicService$.apply(TopicCommand.scala:220)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:57)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:89)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:48)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:455)
	... 5 more
``` 

peter-kafka01 ~ 03 모두 시도 하여보기도하고, 재설치도 하여보았으나 동일하게 나오는 오류를 해결할 수 없었습니다. 
관련하여 앞부분에서 제가 놓친것이 있는지 확인도 해보았으나 발견하지 못했고,
오류를 기반으로 구글링도 해 보았으나 적절한 답변을 찾지 못했습니다.
어떤부분이 문제인지 알려주신다면 감사하겠습니다. 

감사합니다.

**Comment by devms0201** [comment]
자답입니다. 
각 서버의 /etc/hosts를 업데이트 해주니 해결되었습니다.

**Comment by peterko5236** [comment]
안녕하세요 독자님, 

책의 페이지 번호를 확인한 후 답변을 드리려고 했는데, 벌써 해결하셨군요 ^^ 

문의주신 아래 로그는 DNS를 찾을 수 없는 경우에 발생하는 로그로서, 책의 66페이지에서 관련 부분을 언급하고 있습니다. 
 WARN Couldn't resolve server peter-kafka01.foo.bar:9092 from bootstrap.servers as DNS resolution failed for peter-kafka01.foo.bar (org.apache.kafka.clients.ClientUtils)
 
 대부분의 프로덕션 환경에서는 DNS를 등록하여 사용하지만, AWS의 라우터53(DNS서비스)의 경우 쿼리마다 비용이 발생하여 책에서는 부득이하게 /etc/hosts를 수정하여 진행하는 방식으로 했습니다. 
 제 책 구매해주셔서 감사하고, 끝까지 실습과 같이 진행하시다보면 카프카를 이해하시는데 큰 도움이 될 것 입니다. ^^
 진행하시다가 궁금하신 점 있으시면 언제든지 문의 부탁드립니다. 
 
 감사합니다.
